# Generated by Django 5.2.6 on 2025-10-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='帖子标题')),
                ('content', models.TextField(verbose_name='帖子内容')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='回复次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('is_top', models.SmallIntegerField(default=0, verbose_name='是否置顶')),
                ('is_essence', models.SmallIntegerField(default=0, verbose_name='是否精华')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-is_top', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评论内容')),
                ('floor_number', models.IntegerField(verbose_name='楼层')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encyclopedia_app.comment', verbose_name='父评论')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia_app.post', verbose_name='所属帖子')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tieba',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='贴吧名称')),
                ('description', models.TextField(blank=True, verbose_name='贴吧描述')),
                ('avatar', models.CharField(blank=True, max_length=255, verbose_name='贴吧头像')),
                ('category_id', models.IntegerField(blank=True, null=True, verbose_name='分类ID')),
                ('member_count', models.IntegerField(default=0, verbose_name='成员数量')),
                ('post_count', models.IntegerField(default=0, verbose_name='帖子数量')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '贴吧',
                'verbose_name_plural': '贴吧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tieba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia_app.tieba', verbose_name='所属贴吧'),
        ),
    ]
